Repository maxrchung/S2VX, pull requests merged in 2021-02, with the labels that each got.

#351 Tab navigation in command panel
  S2VX.Game.Tests/HeadlessTests/CommandTests.cs
  S2VX.Game.Tests/HeadlessTests/InterpolationTests.cs
  S2VX.Game.Tests/HeadlessTests/ReversibleStackTests.cs
  S2VX.Game.Tests/HeadlessTests/S2VXUtilsTests.cs
  S2VX.Game.Tests/S2VXTestScene.cs
  S2VX.Game.Tests/VisualTests/CommandPanelInputBarTests.cs
  S2VX.Game.Tests/VisualTests/S2VXGameTests.cs
  S2VX.Game.Tests/VisualTests/StoryTests.cs
  S2VX.Game/Editor/Containers/CommandPanel.cs
  S2VX.Game/Editor/Containers/CommandPanelInputBar.cs
  S2VX.Game/Editor/Reversible/ReversibleUpdateCommand.cs
  S2VX.Game/S2VXGame.cs
  S2VX.Game/S2VXGameBase.cs
Labels: feature

#356 Add breaking label
  .github/release-drafter.yml
  .github/workflows/validate-pull-request.yml
Labels: feature

#361 Migrate code analyzers
  .editorconfig
  .github/workflows/continuous-integration.yml
  S2VX.Desktop/Program.cs
  S2VX.Desktop/S2VX.Desktop.csproj
  S2VX.Game.Tests/Program.cs
  S2VX.Game.Tests/S2VX.Game.Tests.csproj
  S2VX.Game/Editor/Containers/NotesTimeline.cs
  S2VX.Game/Editor/Reversible/ReversibleStack.cs
  S2VX.Game/Editor/ToolState/HoldNoteToolState.cs
  S2VX.Game/Editor/ToolState/NoteToolState.cs
  S2VX.Game/S2VX.Game.csproj
  S2VX.Game/Story/Command/S2VXCommand.cs
  S2VX.Game/Story/JSONConverters/CommandConverter.cs
  S2VX.Game/Story/JSONConverters/HoldNoteConverter.cs
  S2VX.Game/Story/JSONConverters/NoteConverter.cs
  S2VX.Game/Story/JSONConverters/Vector2Converter.cs
  S2VX.Resources/S2VX.Resources.csproj
  StoryMerge.Tests/StoryMerge.Tests.csproj
  StoryMerge.Tests/StoryMergerTests.cs
  StoryMerge/CommandsMerger.cs
  StoryMerge/NotesMerger.cs
  StoryMerge/Program.cs
  StoryMerge/StoryMerge.csproj
Labels: feature

#368 Fix old s2ry file crashes
  .editorconfig
  S2VX.Game.Tests/S2VX.Game.Tests.csproj
  S2VX.Game.Tests/VisualTests/SongPreviewTests.cs
  S2VX.Game.Tests/VisualTests/SongPreviewTests/1-second-of-silence.mp3
  S2VX.Game.Tests/VisualTests/SongPreviewTests/EmptyFile.s2ry
  S2VX.Game.Tests/VisualTests/SongPreviewTests/MalformedJSON.s2ry
  S2VX.Game.Tests/VisualTests/SongPreviewTests/MissingEditorSettings.s2ry
  S2VX.Game.Tests/VisualTests/SongPreviewTests/MissingHoldNotes.s2ry
  S2VX.Game.Tests/VisualTests/SongPreviewTests/ValidStory.s2ry
  S2VX.Game/Editor/Containers/CommandPanel.cs
  S2VX.Game/Editor/EditorScreen.cs
  S2VX.Game/Play/PlayScreen.cs
  S2VX.Game/Play/UserInterface/HitErrorDisplay.cs
  S2VX.Game/Play/UserInterface/ScoreInfo.cs
  S2VX.Game/S2VXGameBase.cs
  S2VX.Game/SongSelection/Containers/Border.cs
  S2VX.Game/SongSelection/Containers/SongPreview.cs
  S2VX.Game/SongSelection/SongSelectionScreen.cs
  S2VX.Game/SongSelection/UserInterface/SelectedItemDisplay.cs
  S2VX.Game/Story/Note/EditorHoldNote.cs
  S2VX.Game/Story/Note/HoldNote.cs
  S2VX.Game/Story/S2VXStory.cs
  StoryMerge/InputsLoader.cs
Labels: BIGBUG

#370 Fix hold note approach fade out
  S2VX.Game.Tests/S2VX.Game.Tests.csproj
  S2VX.Game.Tests/VisualTests/EditorHoldNoteTests.cs
  S2VX.Game.Tests/VisualTests/EditorNoteTests.cs
  S2VX.Game.Tests/VisualTests/EditorTests/10-seconds-of-silence.mp3
  S2VX.Game/Story/Note/HoldApproach.cs
Labels: bug

#376 Holding key hits notes in succession
  S2VX.Game.Tests/S2VX.Game.Tests.csproj
  S2VX.Game.Tests/S2VXTestScene.cs
  S2VX.Game.Tests/S2VXTestSceneTestRunner.cs
  S2VX.Game.Tests/VisualTests/EditorHoldNoteTests.cs
  S2VX.Game.Tests/VisualTests/EditorTests/10-seconds-of-silence.mp3
  S2VX.Game.Tests/VisualTests/GameHoldNoteTests.cs
  S2VX.Game.Tests/VisualTests/GameNoteTests.cs
  S2VX.Game.Tests/VisualTests/TestTracks/1-minute-of-silence.mp3
  S2VX.Game.Tests/VisualTests/TestTracks/1-second-of-silence.mp3
  S2VX.Game.Tests/VisualTests/TestTracks/10-seconds-of-silence.mp3
  S2VX.Game/Editor/ToolState/CameraToolState.cs
  S2VX.Game/Play/Containers/InputKeyBindingContainer.cs
  S2VX.Game/Play/InputAction.cs
  S2VX.Game/Play/PlayScreen.cs
  S2VX.Game/Play/UserInterface/ScoreInfo.cs
  S2VX.Game/S2VXUtils.cs
  S2VX.Game/SongSelection/Containers/SongPreview.cs
  S2VX.Game/Story/Note/GameHoldNote.cs
  S2VX.Game/Story/Note/GameNote.cs
  S2VX.Game/Story/S2VXStory.cs
Labels: bug

#381 Note lock
  S2VX.Game.Tests/VisualTests/GameNoteTests.cs
  S2VX.Game/Story/Note/GameNote.cs
  S2VX.Game/Story/Note/Notes.cs
Labels: breaking

#385 Disllow clicks outside MissThreshold for GameNotes
  S2VX.Game.Tests/VisualTests/GameNoteTests.cs
  S2VX.Game/Story/Note/GameHoldNote.cs
  S2VX.Game/Story/Note/GameNote.cs
Labels: bug
