Repository maxrchung/S2VX, pull requests merged in 2021-04, with the labels that each got.

#424 Fix SnapToTick and add tests
  S2VX.Game.Tests/VisualTests/EditorScreenTests/NotesTimelineTests.cs
  S2VX.Game.Tests/VisualTests/EditorScreenTests/ValidStory.s2ry
  S2VX.Game/Editor/Containers/NotesTimeline.cs
  S2VX.Game/Editor/Containers/Timeline.cs
Labels: BIGBUG

#433 Score processor for hold notes
  S2VX.Game.Tests/HeadlessTests/GameHoldNoteTests.cs
  S2VX.Game.Tests/HeadlessTests/S2VXCursorTests/CursorResetTests.cs
  S2VX.Game.Tests/HeadlessTests/ScoreProcessorTests.cs
  S2VX.Game.Tests/HeadlessTests/ScoreProcessorTests/ProcessHitCursorTests.cs
  S2VX.Game.Tests/HeadlessTests/ScoreProcessorTests/ProcessHitSoundTests.cs
  S2VX.Game.Tests/HeadlessTests/ScoreProcessorTests/ProcessHoldCursorTests.cs
  S2VX.Game.Tests/HeadlessTests/ScoreProcessorTests/ProcessHoldSoundTests.cs
  S2VX.Game.Tests/S2VXTestBrowser.cs
  S2VX.Game/Play/Containers/HitErrorBar.cs
  S2VX.Game/Play/UserInterface/ScoreProcessor.cs
  S2VX.Game/Story/Note/GameHoldNote.cs
  S2VX.Game/Story/Note/GameNote.cs
  S2VX.Game/Story/Note/Notes.cs
Labels: breaking

#438 Fix publish release for .net 5
  .github/workflows/publish-release.yml
  S2VX.Desktop/Properties/PublishProfiles/win-x64.pubxml
Labels: BIGBUG

#441 Release for Improve Playability
  .github/workflows/publish-release.yml
  S2VX.Desktop/Properties/PublishProfiles/win-x64.pubxml
  S2VX.Desktop/S2VX.Desktop.csproj
  S2VX.Game.Tests/S2VX.Game.Tests.csproj
  S2VX.Game/S2VX.Game.csproj
  S2VX.Resources/S2VX.Resources.csproj
Labels: BIGBUG

#444 Apply command to note properties and sync Hold Path Color with Outline Color
  .github/workflows/continuous-integration.yml
  S2VX.Game.Tests/HeadlessTests/EditorHoldNoteTests.cs
  S2VX.Game.Tests/HeadlessTests/EditorNoteTests.cs
  S2VX.Game.Tests/VisualTests/EditorHoldNoteTests.cs
  S2VX.Game.Tests/VisualTests/EditorNoteTests.cs
  S2VX.Game.Tests/VisualTests/GameHoldNoteTests.cs
  S2VX.Game.Tests/VisualTests/GameNoteTests.cs
  S2VX.Game/Editor/Containers/NotesTimeline.cs
  S2VX.Game/Editor/ToolState/HoldNoteToolState.cs
  S2VX.Game/Editor/ToolState/NoteToolState.cs
  S2VX.Game/Story/Command/ApproachesColorCommand.cs
  S2VX.Game/Story/Command/HoldApproachesColorCommand.cs
  S2VX.Game/Story/Command/HoldNotesAlphaCommand.cs
  S2VX.Game/Story/Command/HoldNotesColorCommand.cs
  S2VX.Game/Story/Command/HoldNotesOutlineColorCommand.cs
  S2VX.Game/Story/Command/HoldNotesOutlineThicknessCommand.cs
  S2VX.Game/Story/Command/NotesAlphaCommand.cs
  S2VX.Game/Story/Command/NotesColorCommand.cs
  S2VX.Game/Story/Command/NotesOutlineColorCommand.cs
  S2VX.Game/Story/Command/NotesOutlineThicknessCommand.cs
  S2VX.Game/Story/Note/Approach.cs
  S2VX.Game/Story/Note/Approaches.cs
  S2VX.Game/Story/Note/EditorHoldNote.cs
  S2VX.Game/Story/Note/EditorNote.cs
  S2VX.Game/Story/Note/GameHoldNote.cs
  S2VX.Game/Story/Note/GameNote.cs
  S2VX.Game/Story/Note/HoldApproach.cs
  S2VX.Game/Story/Note/HoldNote.cs
  S2VX.Game/Story/Note/Notes.cs
  S2VX.Game/Story/Note/S2VXNote.cs
Labels: feature

#449 Update release-drafter.yml
  .github/release-drafter.yml
Labels: feature

#451 Color input in visual tests
  S2VX.Game.Tests/VisualTests/S2VXColorPickerTests.cs
  S2VX.Game/Editor/ColorPicker/HexTextBox.cs
  S2VX.Game/Editor/ColorPicker/HueSlideContainer.cs
  S2VX.Game/Editor/ColorPicker/PickerAreaContainer.cs
  S2VX.Game/Editor/ColorPicker/S2VXColorPicker.cs
Labels: feature
