Repository maxrchung/S2VX, pull requests merged in 2021-01, with the labels that each got.

#307 Add "Verify Linked Issue" Action
  .github/workflows/validate-pull-request.yml
Labels: feature

#310 Development and release instructions
  .github/workflows/validate-pull-request.yml
Labels: feature

#314 Replaced all interpolation usages with new ClampedInterpolation
  S2VX.Game.Tests/InterpolationTests.cs
  S2VX.Game/S2VXUtils.cs
  S2VX.Game/Story/Command/ApproachesColorCommand.cs
  S2VX.Game/Story/Command/ApproachesDistanceCommand.cs
  S2VX.Game/Story/Command/ApproachesThicknessCommand.cs
  S2VX.Game/Story/Command/BackgroundColorCommand.cs
  S2VX.Game/Story/Command/CameraMoveCommand.cs
  S2VX.Game/Story/Command/CameraRotateCommand.cs
  S2VX.Game/Story/Command/CameraScaleCommand.cs
  S2VX.Game/Story/Command/GridAlphaCommand.cs
  S2VX.Game/Story/Command/GridColorCommand.cs
  S2VX.Game/Story/Command/GridThicknessCommand.cs
  S2VX.Game/Story/Command/HoldApproachesColorCommand.cs
  S2VX.Game/Story/Command/HoldNotesAlphaCommand.cs
  S2VX.Game/Story/Command/HoldNotesColorCommand.cs
  S2VX.Game/Story/Command/HoldNotesOutlineColorCommand.cs
  S2VX.Game/Story/Command/HoldNotesOutlineThicknessCommand.cs
  S2VX.Game/Story/Command/NotesAlphaCommand.cs
  S2VX.Game/Story/Command/NotesColorCommand.cs
  S2VX.Game/Story/Command/NotesFadeInTimeCommand.cs
  S2VX.Game/Story/Command/NotesFadeOutTimeCommand.cs
  S2VX.Game/Story/Command/NotesOutlineColorCommand.cs
  S2VX.Game/Story/Command/NotesOutlineThicknessCommand.cs
  S2VX.Game/Story/Command/NotesShowTimeCommand.cs
  S2VX.Game/Story/Command/TimingChangeCommand.cs
  S2VX.Game/Story/Note/Approach.cs
  S2VX.Game/Story/Note/EditorHoldNote.cs
  S2VX.Game/Story/Note/EditorNote.cs
  S2VX.Game/Story/Note/GameHoldNote.cs
  S2VX.Game/Story/Note/GameNote.cs
  S2VX.Game/Story/Note/HoldApproach.cs
  S2VX.Game/Story/Note/HoldNote.cs
Labels: feature

#330 Make Camera tool Scale relative to current scaling
  S2VX.Game/Editor/ToolState/CameraToolState.cs
Labels: feature

#333 Bigbug label
  .github/release-drafter.yml
  .github/workflows/validate-pull-request.yml
Labels: feature

#338 Remove approach flicker
  S2VX.Game.Tests/InterpolationTests.cs
  S2VX.Game/Story/Command/ApproachesColorCommand.cs
  S2VX.Game/Story/Command/ApproachesDistanceCommand.cs
  S2VX.Game/Story/Command/ApproachesThicknessCommand.cs
  S2VX.Game/Story/Command/CameraMoveCommand.cs
  S2VX.Game/Story/Command/CameraRotateCommand.cs
  S2VX.Game/Story/Command/CameraScaleCommand.cs
  S2VX.Game/Story/Command/GridAlphaCommand.cs
  S2VX.Game/Story/Command/GridColorCommand.cs
  S2VX.Game/Story/Command/GridThicknessCommand.cs
  S2VX.Game/Story/Command/HoldApproachesColorCommand.cs
  S2VX.Game/Story/Command/HoldNotesAlphaCommand.cs
  S2VX.Game/Story/Command/HoldNotesColorCommand.cs
  S2VX.Game/Story/Command/HoldNotesOutlineColorCommand.cs
  S2VX.Game/Story/Command/HoldNotesOutlineThicknessCommand.cs
  S2VX.Game/Story/Command/NotesAlphaCommand.cs
  S2VX.Game/Story/Command/NotesColorCommand.cs
  S2VX.Game/Story/Command/NotesFadeInTimeCommand.cs
  S2VX.Game/Story/Command/NotesFadeOutTimeCommand.cs
  S2VX.Game/Story/Command/NotesOutlineColorCommand.cs
  S2VX.Game/Story/Command/NotesOutlineThicknessCommand.cs
  S2VX.Game/Story/Command/NotesShowTimeCommand.cs
  S2VX.Game/Story/Command/TimingChangeCommand.cs
  S2VX.Game/Story/Note/Approach.cs
  S2VX.Game/Story/Note/Approaches.cs
  S2VX.Game/Story/Note/EditorHoldNote.cs
  S2VX.Game/Story/Note/EditorNote.cs
  S2VX.Game/Story/Note/GameHoldNote.cs
  S2VX.Game/Story/Note/GameNote.cs
  S2VX.Game/Story/Note/HoldApproach.cs
  S2VX.Game/Story/Note/HoldNote.cs
Labels: bug

#340 Grid optimization
  S2VX.Game/Story/Grid.cs
  S2VX.Game/Story/Note/Approach.cs
  S2VX.Game/Story/Note/HoldApproach.cs
Labels: feature

#341 Save hotkey in camera tool
  S2VX.Game/Editor/ToolState/CameraToolState.cs
  S2VX.Game/Story/Note/Approaches.cs
  S2VX.Game/Story/Note/GameHoldNote.cs
Labels: bug

#342 Command out of range handling
  S2VX.Game.Tests/S2VXUtilsTests.cs
  S2VX.Game/S2VXUtils.cs
  S2VX.Game/Story/Command/ApproachesColorCommand.cs
  S2VX.Game/Story/Command/ApproachesDistanceCommand.cs
  S2VX.Game/Story/Command/ApproachesThicknessCommand.cs
  S2VX.Game/Story/Command/BackgroundColorCommand.cs
  S2VX.Game/Story/Command/CameraMoveCommand.cs
  S2VX.Game/Story/Command/CameraRotateCommand.cs
  S2VX.Game/Story/Command/CameraScaleCommand.cs
  S2VX.Game/Story/Command/GridAlphaCommand.cs
  S2VX.Game/Story/Command/GridColorCommand.cs
  S2VX.Game/Story/Command/GridThicknessCommand.cs
  S2VX.Game/Story/Command/HoldApproachesColorCommand.cs
  S2VX.Game/Story/Command/HoldNotesAlphaCommand.cs
  S2VX.Game/Story/Command/HoldNotesColorCommand.cs
  S2VX.Game/Story/Command/HoldNotesOutlineColorCommand.cs
  S2VX.Game/Story/Command/HoldNotesOutlineThicknessCommand.cs
  S2VX.Game/Story/Command/NotesAlphaCommand.cs
  S2VX.Game/Story/Command/NotesColorCommand.cs
  S2VX.Game/Story/Command/NotesFadeInTimeCommand.cs
  S2VX.Game/Story/Command/NotesFadeOutTimeCommand.cs
  S2VX.Game/Story/Command/NotesOutlineColorCommand.cs
  S2VX.Game/Story/Command/NotesOutlineThicknessCommand.cs
  S2VX.Game/Story/Command/NotesShowTimeCommand.cs
  S2VX.Game/Story/Command/S2VXCommand.cs
  S2VX.Game/Story/Command/TimingChangeCommand.cs
Labels: BIGBUG

#347 Copy command in command panel
  S2VX.Game/Editor/Containers/CommandPanel.cs
Labels: feature

#344 Story merge utility
  .editorconfig
  S2VX.Game/Story/Command/S2VXCommand.cs
  S2VX.Game/Story/S2VXStory.cs
  S2VX.sln
  StoryMerge.Tests/CommandTimeInfoTests.cs
  StoryMerge.Tests/CommandsLoaderTests.cs
  StoryMerge.Tests/InputsLoaderTests.cs
  StoryMerge.Tests/NoteTimeInfoTests.cs
  StoryMerge.Tests/NotesMergerTests.cs
  StoryMerge.Tests/ParameterValidatorTests.cs
  StoryMerge.Tests/Samples/ExpectedOutput.s2ry
  StoryMerge.Tests/Samples/GridAlphaFrom0To0.s2ry
  StoryMerge.Tests/Samples/HoldNoteFrom0To1000.s2ry
  StoryMerge.Tests/Samples/HoldNoteFrom500To1500.s2ry
  StoryMerge.Tests/Samples/InvalidStory.s2ry
  StoryMerge.Tests/Samples/NoteAt0.s2ry
  StoryMerge.Tests/Samples/NotesAlphaFrom0To0.s2ry
  StoryMerge.Tests/Samples/NotesAlphaFrom0To1000.s2ry
  StoryMerge.Tests/Samples/NotesAlphaFrom1000To1000.s2ry
  StoryMerge.Tests/Samples/NotesAlphaFrom500To1500.s2ry
  StoryMerge.Tests/StoryMerge.Tests.csproj
  StoryMerge.Tests/StoryMergerTests.cs
  StoryMerge/CommandTimeInfo.cs
  StoryMerge/CommandsMerger.cs
  StoryMerge/InputsLoader.cs
  StoryMerge/NoteTimeInfo.cs
  StoryMerge/NotesMerger.cs
  StoryMerge/ParameterValidator.cs
  StoryMerge/Program.cs
  StoryMerge/Result.cs
  StoryMerge/StoryMerge.csproj
  StoryMerge/StoryMerger.cs
Labels: feature

#345 Add EditorUI visibility container and refactor EditorScreen
  S2VX.Game/Editor/Containers/EditorUI.cs
  S2VX.Game/Editor/EditorScreen.cs
Labels: feature
