Repository maxrchung/S2VX, pull requests merged in 2021-03, with the labels that each got.

#386 Game crashes entering test play
  S2VX.Game.Tests/S2VX.Game.Tests.csproj
  S2VX.Game.Tests/VisualTests/EditorHoldNoteTests.cs
  S2VX.Game.Tests/VisualTests/EditorScreenTests.cs
  S2VX.Game.Tests/VisualTests/EditorScreenTests/ValidStory.s2ry
  S2VX.Game.Tests/VisualTests/GameHoldNoteTests.cs
  S2VX.Game.Tests/VisualTests/GameNoteTests.cs
  S2VX.Game/Editor/EditorScreen.cs
  S2VX.Game/S2VXTrack.cs
  S2VX.Game/S2VXUtils.cs
  S2VX.Game/SongSelection/Containers/SongPreview.cs
  S2VX.Game/Story/S2VXStory.cs
Labels: BIGBUG

#389 Remove setting of Story Clock since the clock is overridden by Editor
  .editorconfig
  S2VX.Game.Tests/VisualTests/EditorHoldNoteTests.cs
  S2VX.Game/Editor/Containers/NotesTimeline.cs
  S2VX.Game/S2VX.Game.csproj
  S2VX.Game/S2VXGame.cs
  S2VX.Game/Story/Note/Approaches.cs
  S2VX.Game/Story/Note/Notes.cs
  S2VX.Game/Story/Note/S2VXNote.cs
  S2VX.Resources/S2VX.Resources.csproj
  S2VX.Resources/S2VXResources.cs
Labels: bug

#396 Hit sound testing
  S2VX.Game.Tests/VisualTests/EditorHoldNoteTests.cs
  S2VX.Game.Tests/VisualTests/EditorNoteTests.cs
  S2VX.Game/Editor/EditorScreen.cs
  S2VX.Game/S2VXSample.cs
  S2VX.Game/Story/Note/EditorHoldNote.cs
  S2VX.Game/Story/Note/EditorNote.cs
  S2VX.Game/Story/Note/GameHoldNote.cs
  S2VX.Game/Story/Note/GameNote.cs
Labels: feature

#394 Change hold note scoring
  S2VX.Game.Tests/VisualTests/EditorHoldNoteTests.cs
  S2VX.Game.Tests/VisualTests/EditorNoteTests.cs
  S2VX.Game.Tests/VisualTests/GameHoldNoteTests.cs
  S2VX.Game/Editor/Reversible/ReversibleAddHoldNote.cs
  S2VX.Game/Editor/Reversible/ReversibleRemoveHoldNote.cs
  S2VX.Game/Story/Note/GameHoldNote.cs
  S2VX.Game/Story/Note/HoldNoteState.cs
  S2VX.Game/Story/S2VXStory.cs
  StoryMerge/NotesMerger.cs
Labels: breaking

#403 Hold note lock
  S2VX.Game.Tests/VisualTests/GameHoldNoteTests.cs
  S2VX.Game.Tests/VisualTests/GameNoteTests.cs
  S2VX.Game/Story/Note/GameHoldNote.cs
  S2VX.Game/Story/Note/GameNote.cs
Labels: breaking

#405 Separate HeadlessTests from VisualTests
  S2VX.Game.Tests/HeadlessTests/EditorHoldNoteTests.cs
  S2VX.Game.Tests/HeadlessTests/EditorNoteTests.cs
  S2VX.Game.Tests/HeadlessTests/GameHoldNoteTests.cs
  S2VX.Game.Tests/HeadlessTests/GameNoteTests.cs
  S2VX.Game.Tests/S2VX.Game.Tests.csproj
  S2VX.Game.Tests/TestTracks/1-minute-of-silence.mp3
  S2VX.Game.Tests/TestTracks/1-second-of-silence.mp3
  S2VX.Game.Tests/TestTracks/10-seconds-of-silence.mp3
  S2VX.Game.Tests/UnitTests/CommandTests.cs
  S2VX.Game.Tests/UnitTests/InterpolationTests.cs
  S2VX.Game.Tests/UnitTests/ReversibleStackTests.cs
  S2VX.Game.Tests/UnitTests/S2VXUtilsTests.cs
  S2VX.Game.Tests/VisualTests/EditorHoldNoteTests.cs
  S2VX.Game.Tests/VisualTests/EditorNoteTests.cs
  S2VX.Game.Tests/VisualTests/EditorScreenTests.cs
  S2VX.Game.Tests/VisualTests/GameHoldNoteTests.cs
  S2VX.Game.Tests/VisualTests/GameNoteTests.cs
Labels: feature

#409 Remove red indication on notes
  S2VX.Game/Story/Note/GameHoldNote.cs
  S2VX.Game/Story/Note/GameNote.cs
Labels: bug

#412 Hide hit error bar
  S2VX.Game.Tests/VisualTests/PlayInfoBarTests.cs
  S2VX.Game/Play/Containers/HitErrorBar.cs
  S2VX.Game/Play/PlayScreen.cs
  S2VX.Game/Story/Note/GameHoldNote.cs
  S2VX.Game/Story/Note/GameNote.cs
Labels: feature

#408 Cursor color rotation scale
  S2VX.Game.Tests/HeadlessTests/S2VXCursorTests/CursorReset.cs
  S2VX.Game.Tests/S2VXTestScene.cs
  S2VX.Game.Tests/S2VXTestSceneTestRunner.cs
  S2VX.Game.Tests/VisualTests/S2VXCursorTests/CursorDefaults.cs
  S2VX.Game.Tests/VisualTests/S2VXCursorTests/CursorUpdates.cs
  S2VX.Game.Tests/VisualTests/S2VXGameTests.cs
  S2VX.Game.Tests/VisualTests/StoryTests.cs
  S2VX.Game/Editor/Containers/CommandPanel.cs
  S2VX.Game/Editor/Containers/CommandPanelInputBar.cs
  S2VX.Game/Editor/EditorScreen.cs
  S2VX.Game/Play/PlayScreen.cs
  S2VX.Game/S2VXColorConstants.cs
  S2VX.Game/S2VXCursor.cs
  S2VX.Game/S2VXGame.cs
  S2VX.Game/S2VXGameBase.cs
  S2VX.Game/SongSelection/SongSelectionScreen.cs
  S2VX.Game/SongSelection/UserInterface/SelectedItemDisplay.cs
  S2VX.Game/Story/S2VXStory.cs
Labels: breaking

#415 Global setting to hide hit errors and score
  S2VX.Game.Tests/S2VXTestSceneTestRunner.cs
  S2VX.Game.Tests/VisualTests/PlayInfoBarTests.cs
  S2VX.Game/Configuration/S2VXConfigManager.cs
  S2VX.Game/Play/Containers/InputKeyBindingContainer.cs
  S2VX.Game/Play/Containers/PlayKeyBindingContainer.cs
  S2VX.Game/Play/InputAction.cs
  S2VX.Game/Play/PlayAction.cs
  S2VX.Game/Play/PlayScreen.cs
  S2VX.Game/S2VXGameBase.cs
  S2VX.Game/Story/Note/GameHoldNote.cs
  S2VX.Game/Story/Note/GameNote.cs
Labels: feature

#413 Fix visibility of song preview tests
  S2VX.Game.Tests/HeadlessTests/SongPreviewTests/1-second-of-silence.mp3
  S2VX.Game.Tests/HeadlessTests/SongPreviewTests/EmptyFile.s2ry
  S2VX.Game.Tests/HeadlessTests/SongPreviewTests/MalformedJSON.s2ry
  S2VX.Game.Tests/HeadlessTests/SongPreviewTests/MissingEditorSettings.s2ry
  S2VX.Game.Tests/HeadlessTests/SongPreviewTests/MissingHoldNotes.s2ry
  S2VX.Game.Tests/HeadlessTests/SongPreviewTests/StoryLoadTests.cs
  S2VX.Game.Tests/HeadlessTests/SongPreviewTests/ValidStory.s2ry
  S2VX.Game.Tests/S2VX.Game.Tests.csproj
  S2VX.Game.Tests/S2VXTestBrowser.cs
  S2VX.Game.Tests/S2VXTestSceneTestRunner.cs
  S2VX.Game.Tests/VisualTests/EditorScreenTests/PreviewGameTests.cs
  S2VX.Game.Tests/VisualTests/S2VXCursorTests/CursorDefaultTests.cs
  S2VX.Game.Tests/VisualTests/S2VXCursorTests/CursorUpdateTests.cs
  S2VX.Game/S2VXGame.cs
  S2VX.Game/S2VXGameBase.cs
  S2VX.Game/SongSelection/Containers/SongPreview.cs
Labels: bug

#416 Score processor for regular notes
  S2VX.Game.Tests/HeadlessTests/GameHoldNoteTests.cs
  S2VX.Game.Tests/HeadlessTests/GameNoteTests.cs
  S2VX.Game.Tests/HeadlessTests/ScoreProcessorTests.cs
  S2VX.Game.Tests/VisualTests/GameHoldNoteTests.cs
  S2VX.Game.Tests/VisualTests/GameNoteTests.cs
  S2VX.Game.Tests/VisualTests/PlayInfoBarTests.cs
  S2VX.Game.Tests/VisualTests/S2VXCursorTests/CursorDefaultTests.cs
  S2VX.Game/Play/PlayScreen.cs
  S2VX.Game/Play/UserInterface/ScoreInfo.cs
  S2VX.Game/Play/UserInterface/ScoreProcessor.cs
  S2VX.Game/S2VXColorConstants.cs
  S2VX.Game/S2VXCursor.cs
  S2VX.Game/S2VXSample.cs
  S2VX.Game/Story/Note/GameHoldNote.cs
  S2VX.Game/Story/Note/GameNote.cs
  S2VX.Game/Story/Note/Notes.cs
Labels: breaking
